name: "PR"

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # `yarn test` takes long time
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        shell: bash
        run: yarn --prefer-offline
      - name: Build
        shell: bash
        run: yarn build
      - run: yarn format
      - name: Check format
        run: |
          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "All files formatted"
          else
            echo "Running format is required"
            exit 1
          fi
      - name: Validate configuration
        run: yarn validate-config
      - name: Test
        shell: bash
        run: yarn test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          platforms: linux/amd64
